try {
    console.log('1');
} catch (error) {
    console.log('error!');
}
console.log('after try catch');